version: "3"
services:
    db:
        container_name: mydb
        image: mysql:latest
        ports:
            - "3307:3307"
        environment:
            MYSQL_ROOT_PASSWORD: Nirfakiro97$!
    app:
        container_name: listify
        links:
            - "db"
        build: ./
        ports:
            - "5000:5000"
